export const locconfig = {
  version: "bf712017",
  applicationType: "app",
  authType: "Bearer",
  token: "18d376f7267ba45502903a763b4461c95c5cac82",
  adaChatbotIDToken: "None",
  staticBaseURL: "https://pd-app-staging.s3-eu-west-1.amazonaws.com/",
  webBaseURL: "https://app.stg17.sealdocs.com/",
  eFormURL: "https://eform-dyn-env.dev.sealdocs.com/stg17/",
  editorV2PublicViewURL: "https://app.stg17.sealdocs.com/p/",
  editorV2URL: "https://app.stg17.sealdocs.com/e/",
  storeURL: "https://store.stg17.sealdocs.com/",
  storeWebURL: "https://app.stg17.sealdocs.com/store/",
  notaryUrl: "https://notary.stg17.sealdocs.com/",
  liveSessionUrl: "https://meet.stg17.sealdocs.com/",
  APIBaseURL: "https://api.stg17.sealdocs.com/",
  contentAPIURL: "wss://websocket.stg17.sealdocs.com/ws",
  contentAPISSEURL: "https://websocket.stg17.sealdocs.com/sse",
  contentAPICheckURL: "https://websocket.stg17.sealdocs.com/static/1x1.gif",
  contentAPIURLReserved:
    "wss://websocket-reserved.stg17.sealdocs.com/ws-reserved",
  contentAPIUser: "iq8Ehpl7V7u5FsKMEOtRBkllKrxX9pHXN0PqqUVOnh0=",
  contentAPIKey: "S4LBWAIL+RBUlW3NDodJfg==",
  monitoringURL: "https://prom-fe-gw.development.pandadoc.com/metrics/",
  faroCollectorURL:
    "https://grafana-agent-faro.development.pandadoc.com/collect",
  sentryDsnURL:
    "https://f4186af9a2bc4f21915c01e57cb5ee11@sentry.infrastructure.pandadoc.com/43",
  editorSentryDsnURL:
    "https://55bb7ea08d8044adac37b6739ed46331@sentry.infrastructure.pandadoc.com/202",
  userMediaURL: "pandadoc-dev-media",
  iframelyBaseURL: "https://cdn.iframe.ly/api/",
  iframelyKey: "dbbf6d6a21a56f843994798b9c66d9cc",
  staticStorageBucketName: "pd-ws-static-staging",
  environment: "stg17",
  user_type: 2,
  pusherKey: "72e976c39ed6d9e81643",
  pusherCluster: "mt1",
  pusherChannel:
    "234a118396bc1222364cd0cee7220fc1fdcf590ceb79b32844788e63e6508a0f",
  googleDriveOAuth2URL: "/auth/login/google-oauth2/",
  docProcessorStaticBaseURL:
    "https://doc-processor-staging.s3.amazonaws.com/documents/",
  googleDriveAssoc: false,
  isAnalyticsEnabled: false,
  segment_write_key: "shtMPWEV1r4lPg9Latl7BrbKW7ghmwvh",
  isWootricEnabled: false,
  document_analytics_token: "12-nG567hsB-te5478nub_3457y",
  document_analytics_host: "https://analytics.stg17.sealdocs.com",
  intercom_hmac_token:
    "742ef04859e1d4ba8c1beb061ec8bdf5748fb97acd9dd74d4c0f22656d1df5a4",
  inAppHelp: {
    faqEmbedUrl: "123456",
  },
  mailgunEmailValidationPubKey: "pubkey-f9c742a61340560d2bbfc0a89aa6e137",
  canvaPublicAPIKey: "IDHVKiLHLEIF-xo7-rNCHloU",
  liveSessionClientId: "IjG9g4FXZHILGWFshjZOzAZpn9liqNXeJW1bopoi",
  resourcesUrl:
    "https://pd-staging-product-updates.s3-us-west-2.amazonaws.com/",
  workspace: "D9XV6jHaVSEZJzDSjgmaVi",
  organization: "BbDZUsjFgXZgEiZ6aheVTQ",
  features: [],
  permissions: [
    "can_edit_own_forms",
    "can_read_rooms",
    "can_view_any_process_templates",
    "can_send_any_payment_reminder",
    "can_apply_theme_to_document",
    "can_edit_any_template_folder",
    "can_change_branding",
    "can_move_clis",
    "can_read_images",
    "can_move_templates",
    "can_view_any_notarization_request",
    "can_create_document_folders",
    "can_edit_any_forms",
    "can_mark_as_paid_any",
    "can_publish_any_forms",
    "can_download_documents",
    "can_create_forms",
    "can_publish_eforms",
    "can_view_notaries",
    "can_edit_images",
    "can_duplicate_own_process_templates",
    "can_move_any_process_templates",
    "can_create_images",
    "can_publish_any_eform",
    "can_remove_rooms",
    "can_edit_metadata_fields",
    "can_edit_template_approval",
    "can_create_metadata_document_type",
    "can_view_smart_content_for_recipients",
    "can_add_users",
    "can_access_reporting",
    "can_publish_own_forms",
    "can_edit_any_room",
    "can_remove_users",
    "can_remove_own_process_templates",
    "can_delete_saved_messages",
    "can_read_saved_messages",
    "can_read_webhook_subscription_events",
    "can_create_uploaded_templates",
    "can_manage_smart_content_for_recipients",
    "can_create_documents_from_own_forms",
    "can_configure_quotes",
    "can_remove_any_cli",
    "can_create_catalog_items",
    "can_create_contact_groups",
    "can_remove_any_eform",
    "can_create_metadata_fields",
    "can_update_webhook_subscriptions",
    "can_read_any_document_folder",
    "can_remove_any_template",
    "can_move_any_document_folder",
    "can_view_integrations",
    "can_remove_any_process_entities_in_workspace",
    "can_view_process_entities_when_participating",
    "can_read_cli_folders",
    "can_edit_cli_folders",
    "can_remove_document_metadata_fields",
    "can_edit_any_document",
    "can_remove_eforms",
    "can_view_any_payments",
    "can_duplicate_any_template",
    "can_read_documents",
    "can_read_themes",
    "can_edit_any_eform",
    "can_publish_any_room",
    "can_read_document_folders",
    "can_create_documents_from_any_forms",
    "can_create_saved_messages",
    "can_select_metadata_document_type_for_template",
    "can_edit_any_saved_message",
    "can_create_cli_folders",
    "can_create_contacts",
    "can_change_workspace_settings",
    "can_create_document_in_any_folder",
    "can_view_any_process_entities",
    "can_remove_any_process_templates",
    "can_start_process_entities_from_process_templates",
    "can_delete_webhook_subscriptions",
    "can_move_document_folder_to_any_folder",
    "can_remove_any_document",
    "can_move_any_template",
    "can_edit_users",
    "can_duplicate_any_process_templates",
    "can_read_catalog_items",
    "can_manage_integrations",
    "can_publish_rooms",
    "can_archive_metadata_document_type",
    "can_edit_catalog_items",
    "can_remove_clis",
    "can_create_documents_from_shared_templates",
    "can_edit_document_approval",
    "can_create_documents_from_public_templates",
    "can_manage_rules",
    "can_read_eforms",
    "can_edit_any_cli_folder",
    "can_select_metadata_document_type_for_document",
    "can_remove_contacts",
    "can_duplicate_templates",
    "can_add_template_metadata_fields",
    "can_approve_documents",
    "can_edit_room_templates",
    "can_remove_documents",
    "can_move_documents",
    "can_edit_own_process_entities",
    "can_edit_any_template",
    "can_view_own_process_templates",
    "can_remove_themes",
    "can_move_own_process_templates",
    "can_remove_any_template_folder",
    "can_create_webhook_subscriptions",
    "can_mark_as_paid",
    "can_remove_templates",
    "can_remove_catalog_folders",
    "can_filter_dashboard_by_team_member",
    "can_view_rules",
    "can_edit_quotes",
    "can_edit_template_folders",
    "can_send_documents",
    "can_edit_contacts",
    "can_remove_any_document_folder",
    "can_remove_contact_groups",
    "can_remove_document_folders",
    "can_skip_document_approval",
    "can_delete_any_image",
    "can_edit_metadata_values",
    "can_read_template_folders",
    "can_edit_any_notarization_request",
    "can_remove_room_templates",
    "can_share_clis",
    "can_share_templates",
    "can_delete_any_saved_message",
    "can_edit_clis",
    "can_remove_any_cli_folder",
    "can_create_uploaded_documents",
    "can_move_catalog_items",
    "can_create_clis",
    "can_remove_notaries",
    "can_embed_templates",
    "can_create_document_folder_in_any_folder",
    "can_edit_any_process_entities",
    "can_read_webhook_subscriptions",
    "can_view_payments",
    "can_edit_any_image",
    "can_send_payment_reminder",
    "can_create_room_templates",
    "can_move_any_cli",
    "can_lock_content",
    "can_create_template_folders",
    "can_edit_document_folders",
    "can_create_catalog_folders",
    "can_read_catalog_folders",
    "can_publish_themes",
    "can_view_forms",
    "can_edit_themes",
    "can_read_contact_groups",
    "can_apply_theme_to_template",
    "can_duplicate_eforms",
    "can_edit_any_document_folder",
    "can_edit_any_process_templates",
    "can_create_themes",
    "can_add_document_metadata_fields",
    "can_delete_images",
    "can_duplicate_any_cli",
    "can_create_blank_documents",
    "can_edit_any_cli",
    "can_remove_own_process_entities",
    "can_manage_quote_products",
    "can_move_any_document",
    "can_edit_metadata_document_type",
    "can_edit_saved_messages",
    "can_read_templates",
    "can_add_notaries",
    "can_create_eforms",
    "can_host_in_person_signing_sessions",
    "can_manage_content_placeholder",
    "can_view_room_templates",
    "can_duplicate_clis",
    "can_read_clis",
    "can_edit_own_process_templates",
    "can_send_any_document",
    "can_edit_catalog_folders",
    "can_edit_contact_groups",
    "can_move_document_folders",
    "can_edit_eforms",
    "can_archive_metadata_fields",
    "can_download_clis",
    "can_duplicate_any_eform",
    "can_download_templates",
    "can_edit_rooms",
    "can_regenerate_webhook_subscription_shared_key",
    "can_remove_template_metadata_fields",
    "can_remove_cli_folders",
    "can_read_contacts",
    "can_move_document_to_any_folder",
    "can_remove_template_folders",
    "can_remove_catalog_items",
    "can_create_documents_from_templates",
    "can_edit_documents",
    "can_view_any_room",
    "can_view_own_process_entities",
    "can_remove_any_room",
    "can_create_documents",
    "can_create_own_process_templates",
    "can_edit_templates",
    "can_read_any_document",
    "can_create_rooms",
    "can_import_catalog_items",
  ],
  automationsWorkatoOrigin: "https://www.workato.com",
  moduleFederations: {
    APIDashboard:
      "https://static.dev.sealdocs-static.com/stg17/appjs-api-dashboard/aa47ce31/remoteEntry.js",
    DocumentWizard:
      "https://static.dev.sealdocs-static.com/stg17/appjs-document-wizard/b1f332ec/remoteEntry.js",
    Home: "https://static.dev.sealdocs-static.com/stg17/appjs-home/d7d3f818/remoteEntry.js",
    WorkflowAutomation:
      "https://static.dev.sealdocs-static.com/stg17/appjs-automations/ee283a6a/remoteEntry.js",
    Catalog:
      "https://static.dev.sealdocs-static.com/stg17/appjs-catalog/c643184d/remoteEntry.js",
    Notifications:
      "https://static.dev.sealdocs-static.com/stg17/appjs-notifications/eef2d53c/remoteEntry.js",
    ProcessBuilder:
      "https://static.dev.sealdocs-static.com/stg17/appjs-process-builder/71958e09/remoteEntry.js",
    ProcessGallery:
      "https://static.dev.sealdocs-static.com/stg17/appjs-process-gallery/930baa21/remoteEntry.js",
    PDForm:
      "https://static.dev.sealdocs-static.com/stg17/appjs-pd-form/86acc1a3/remoteEntry.js",
    TemplateSelector:
      "https://static.dev.sealdocs-static.com/stg17/appjs-template-selector/a38b82c1/remoteEntry.js",
    Metadata:
      "https://static.dev.sealdocs-static.com/stg17/appjs-metadata/7f216c66/remoteEntry.js",
    DocumentInfo:
      "https://static.dev.sealdocs-static.com/stg17/appjs-document-info/1b6e074d/remoteEntry.js",
    Quote:
      "https://static.dev.sealdocs-static.com/stg17/appjs-quote/440b9aa4/remoteEntry.js",
    Paywall:
      "https://static.dev.sealdocs-static.com/stg17/appjs-paywall/9eada146/remoteEntry.js",
    CancellationFlow:
      "https://static.dev.sealdocs-static.com/stg17/appjs-cancellation-flow/874ceec6/remoteEntry.js",
    Room: "https://static.dev.sealdocs-static.com/stg17/appjs-room/f2abd2f0/remoteEntry.js",
    PDFToolkit:
      "https://static.dev.sealdocs-static.com/stg17/appjs-pdf-toolkit/4cf80cf4/remoteEntry.js",
    Store:
      "https://static.dev.sealdocs-static.com/stg17/appjs-store/c49db553/remoteEntry.js",
    CurrencyFormatter:
      "https://static.dev.sealdocs-static.com/stg17/appjs-currency-formatter/48d5e84c/remoteEntry.js",
    QuoteDataMerge:
      "https://static.dev.sealdocs-static.com/stg17/appjs-quote/quote-data-merge-configurator/440b9aa4/remoteEntry.js",
    AiPrompt:
      "https://static.dev.sealdocs-static.com/stg17/appjs-ai-prompt/683b3e83/remoteEntry.js",
    Billing:
      "https://static.dev.sealdocs-static.com/stg17/appjs-billing/72685370/remoteEntry.js",
    Settings:
      "https://static.dev.sealdocs-static.com/stg17/appjs-settings/f50fd05b/remoteEntry.js",
    BillingInfo:
      "https://static.dev.sealdocs-static.com/stg17/appjs-billing-info/94562f37/remoteEntry.js",
    PaymentDetails:
      "https://static.dev.sealdocs-static.com/stg17/appjs-payment-details/555083eb/remoteEntry.js",
    PaymentsDashboard:
      "https://static.dev.sealdocs-static.com/stg17/appjs-payments/c3068104/remoteEntry.js",
    Inquirer:
      "https://static.dev.sealdocs-static.com/stg17/libjs-inquirer/104ffc83/remoteEntry.js",
    RuleConfigurator:
      "https://static.dev.sealdocs-static.com/stg17/appjs-rule-configurator/d066d61a/remoteEntry.js",
    KbaVerification:
      "https://static.dev.sealdocs-static.com/stg17/appjs-kba/015e5f5d/remoteEntry.js",
    RuleEngine:
      "https://static.dev.sealdocs-static.com/stg17/appjs-rule-engine/22134a68/remoteEntry.js",
    Preonboarding:
      "https://static.dev.sealdocs-static.com/stg17/appjs-preonboarding/d4ab8eb1/remoteEntry.js",
    LookupTables:
      "https://static.dev.sealdocs-static.com/stg17/appjs-lookup-tables/9be7e11d/remoteEntry.js",
    DocumentOperations:
      "https://pd-app-staging.s3-eu-west-1.amazonaws.com/scripts/appjs-kolas-editor/document-operations/remoteEntry.7f74db64.js",
    SessionWizard:
      "https://static.dev.sealdocs-static.com/stg17/appjs-session-wizard/5016cff2/remoteEntry.js",
    Notary:
      "https://static.dev.sealdocs-static.com/stg17/appjs-notary/de062769/remoteEntry.js",
  },
  is_organization_owner: false,
  billingPusherChannel:
    "2753467de5572c1799b78e5362e9bbe1a762d080fe05cfc24fcd4801d6e6c50d",
  userRole: 1,
  has_docs: false,
  rootDomain: "stg17.sealdocs.com",
  uppyCompanionURL: "https://uppy.stg17.sealdocs.com/",
  quickbooksTokenizeUrl:
    "https://sandbox.api.intuit.com/quickbooks/v4/payments/tokens",
  new_onboarding_shown_times: "1",
};
